name: Pipeline Desarrollo Seguro

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sast:
    name: SAST Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: Upload SonarCloud Report
        uses: actions/upload-artifact@v4
        with:
          name: sonarcloud-report
          path: .scannerwork/report-task.txt

      - name: Bandit Security Scan (Python)
        run: |
          pip install bandit
          bandit -r . --severity-level high -f html -o bandit-report.html
        continue-on-error: true

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.html

  sca:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    needs: [sast]
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        id: depcheck
        with:
          project: 'tfm-pruebas'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: '--failOnCVSS 7 --enableRetired'

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: Dependency-Check Report
          path: reports

  dast:
    name: DAST Analysis
    runs-on: ubuntu-latest
    needs: [sast, sca] # Se ejecuta después de SAST y SCA
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build app Docker image
        run: |
          docker build -t myapp .

      - name: Run app in detached mode
        run: |
          docker run -d --rm --name myapp -p 5000:5000 myapp
          sleep 10
       
      - name: Scan with nikto
        uses: thereisnotime/action-nikto@master
        with:
          url: "http://localhost:5000"

      - name: Upload Nikto Report
        uses: actions/upload-artifact@v4
        with:
          name: nikto-report
          path: nikto-report.html

      - name: OWASP ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: "http://myapp:5000"
          fail_action: false # No falla el pipeline si hay vulnerabilidades


      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report.json

      - name: Stop Web Application
        run: |
          docker stop myapp